// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: protos/random.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RandNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed  int64 `protobuf:"varint,1,opt,name=Seed,proto3" json:"Seed,omitempty"`
	Place int64 `protobuf:"varint,2,opt,name=Place,proto3" json:"Place,omitempty"`
}

func (x *RandNumRequest) Reset() {
	*x = RandNumRequest{}
	mi := &file_protos_random_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandNumRequest) ProtoMessage() {}

func (x *RandNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_random_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandNumRequest.ProtoReflect.Descriptor instead.
func (*RandNumRequest) Descriptor() ([]byte, []int) {
	return file_protos_random_proto_rawDescGZIP(), []int{0}
}

func (x *RandNumRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *RandNumRequest) GetPlace() int64 {
	if x != nil {
		return x.Place
	}
	return 0
}

type RandNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (x *RandNumResponse) Reset() {
	*x = RandNumResponse{}
	mi := &file_protos_random_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandNumResponse) ProtoMessage() {}

func (x *RandNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_random_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandNumResponse.ProtoReflect.Descriptor instead.
func (*RandNumResponse) Descriptor() ([]byte, []int) {
	return file_protos_random_proto_rawDescGZIP(), []int{1}
}

func (x *RandNumResponse) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type RandPassRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed   int64 `protobuf:"varint,1,opt,name=Seed,proto3" json:"Seed,omitempty"`
	Length int64 `protobuf:"varint,2,opt,name=Length,proto3" json:"Length,omitempty"`
}

func (x *RandPassRequest) Reset() {
	*x = RandPassRequest{}
	mi := &file_protos_random_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandPassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandPassRequest) ProtoMessage() {}

func (x *RandPassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_random_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandPassRequest.ProtoReflect.Descriptor instead.
func (*RandPassRequest) Descriptor() ([]byte, []int) {
	return file_protos_random_proto_rawDescGZIP(), []int{2}
}

func (x *RandPassRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *RandPassRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type RandPassResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pass string `protobuf:"bytes,1,opt,name=Pass,proto3" json:"Pass,omitempty"`
}

func (x *RandPassResponse) Reset() {
	*x = RandPassResponse{}
	mi := &file_protos_random_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandPassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandPassResponse) ProtoMessage() {}

func (x *RandPassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_random_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandPassResponse.ProtoReflect.Descriptor instead.
func (*RandPassResponse) Descriptor() ([]byte, []int) {
	return file_protos_random_proto_rawDescGZIP(), []int{3}
}

func (x *RandPassResponse) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

var File_protos_random_proto protoreflect.FileDescriptor

var file_protos_random_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x61, 0x6e, 0x64,
	0x22, 0x3a, 0x0a, 0x0e, 0x52, 0x61, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x53, 0x65, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x22, 0x23, 0x0a, 0x0f,
	0x52, 0x61, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e, 0x75,
	0x6d, 0x22, 0x3d, 0x0a, 0x0f, 0x52, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x53, 0x65, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x22, 0x26, 0x0a, 0x10, 0x52, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x73, 0x73, 0x32, 0x95, 0x01, 0x0a, 0x06, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x12, 0x43, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x4e, 0x75,
	0x6d, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x61, 0x6e, 0x64, 0x2e, 0x52, 0x61,
	0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x61, 0x6e, 0x64, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x4e, 0x75, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x6e, 0x64, 0x50, 0x61, 0x73, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x61, 0x6e, 0x64, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x61, 0x6e, 0x64, 0x2e,
	0x52, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_random_proto_rawDescOnce sync.Once
	file_protos_random_proto_rawDescData = file_protos_random_proto_rawDesc
)

func file_protos_random_proto_rawDescGZIP() []byte {
	file_protos_random_proto_rawDescOnce.Do(func() {
		file_protos_random_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_random_proto_rawDescData)
	})
	return file_protos_random_proto_rawDescData
}

var file_protos_random_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_random_proto_goTypes = []any{
	(*RandNumRequest)(nil),   // 0: protoRand.RandNumRequest
	(*RandNumResponse)(nil),  // 1: protoRand.RandNumResponse
	(*RandPassRequest)(nil),  // 2: protoRand.RandPassRequest
	(*RandPassResponse)(nil), // 3: protoRand.RandPassResponse
}
var file_protos_random_proto_depIdxs = []int32{
	0, // 0: protoRand.Random.GetRandNum:input_type -> protoRand.RandNumRequest
	2, // 1: protoRand.Random.GetRandPass:input_type -> protoRand.RandPassRequest
	1, // 2: protoRand.Random.GetRandNum:output_type -> protoRand.RandNumResponse
	3, // 3: protoRand.Random.GetRandPass:output_type -> protoRand.RandPassResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_random_proto_init() }
func file_protos_random_proto_init() {
	if File_protos_random_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_random_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_random_proto_goTypes,
		DependencyIndexes: file_protos_random_proto_depIdxs,
		MessageInfos:      file_protos_random_proto_msgTypes,
	}.Build()
	File_protos_random_proto = out.File
	file_protos_random_proto_rawDesc = nil
	file_protos_random_proto_goTypes = nil
	file_protos_random_proto_depIdxs = nil
}
